FROM node:20

COPY . .

RUN npm install && npm run build

CMD ["npm", "start"]

# imagen resultante

# 1- node
# 2- npm
# 3- build tools (a herramientras de construccion)
# 4- dependencia dev (codigo)