# FROM alpine

# ARG VERSION

# ENV VERSION=$VERSION

# CMD echo "VERSION: $VERSION"

ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine


## recomendacion para cada imagen, se sugiere etiquetar con lo siguiente:
    ## docker build -t miapp .


    ## docker tag miapp fercdevv/miapp:1.0
    ## docker docker push fercdevv/miapp:1.0